name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
      - uses: actions/checkout@v2
    
      - name: Deploy Stack
      - uses: kgierke/portainer-stack-deployment@v1
        with:
          portainer-url: ${{ secrets.PORTAINER_HOST }}
          portainer-username: ${{ secrets.PORTAINER_USERNAME }}
          portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
          portainer-endpoint: 2
          name: tobbflix
          file: tobbflix/docker-compose.yml
          variables: '{"plex_claim": "${{ secrets.TOBBFLIX_PLEX_CLAIM }}", "transmission_user": "${{ secrets.TOBBFLIX_TRANSMISSION_USER }}", "transmission_password": "${{ secrets.TOBBFLIX_TRANSMISSION_PASSWORD }}"}' # Change vars to secrets 
