name: Deploy
on:
  push:
    branches:
      - bugfix
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Deploy Stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'tobbflix'
          stack-definition: 'tobbflix/docker-compose.yml'
          template-variables: '{"PLEX_CLAIM": "${{ secrets.TOBBFLIX_PLEX_CLAIM }}"}'
<<<<<<< HEAD
          # env:
          #   PLEX_CLAIM: ${{ secrets.TOBBFLIX_PLEX_CLAIM }}
          #   TRANSMISSION_USER: ${{ secrets.TOBBFLIX_TRANSMISSION_USER }}
          #   TRANSMISSION_PASSWORD: ${{ secrets.TOBBFLIX_TRANSMISSION_PASSWORD }}
=======
        env:
          PLEX_CLAIM: ${{ secrets.TOBBFLIX_PLEX_CLAIM }}
          TRANSMISSION_USER: ${{ secrets.TOBBFLIX_TRANSMISSION_USER }}
          TRANSMISSION_PASSWORD: ${{ secrets.TOBBFLIX_TRANSMISSION_PASSWORD }}
>>>>>>> e53fbec9990cd319dbcc0af60f6e1071dd009834
